
= BookGen

== Brief Introduction

BookGen is
a minimal, single-header ANSI C library for generating
semantic, well-indented HTML documents programmatically.

It's a simple collection of C functions that emit HTML tags.

The goal is to enable developers to create HTML using the features of a programming language:

* reusable HTML components using functions and macros,
* variables and constants,
* loops and conditionals,
* and so on!

Even though it's a single-header library
and aims to be completely self-sufficient,
it comes with a few CSS styles that make the resulting HTML
way more professional looking.

The library aims at being useful to C developers
met with HTML's common tags and attributes
intending to give their documentation, reports, essays, books, etc.
a professional look using a minimal and extermely maintainable library.

Enjoy!

== Usage Example

The usage example is defined in `example.c` and is compiled using `make`.

The library contains a _lot_ of functions,
so I invite you to browse through the library and see
what it has to offer.

== Styles

There are a couple stylesheets in the `styles` folder, namely
the base file, which contains all the general styling,
and the light and dark mode file, which define the color variables used in the base file.

The general usage is to include the base file and whatever colorscheme you choose.
This allows easily creating any colorscheme you'd like!

